# Generated by Django 5.1.5 on 2025-02-26 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calificaciones',
            fields=[
                ('id_calificacion', models.AutoField(db_column='ID_Calificacion', primary_key=True, serialize=False)),
                ('calificacion', models.DecimalField(blank=True, db_column='Calificacion', decimal_places=1, max_digits=2, null=True)),
            ],
            options={
                'db_table': 'calificaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cuestionarios',
            fields=[
                ('id_cuestionario', models.AutoField(db_column='ID_Cuestionario', primary_key=True, serialize=False)),
                ('titulocuestionario', models.CharField(blank=True, db_column='TituloCuestionario', max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, db_column='Descripcion', null=True)),
                ('esdiagnostico', models.IntegerField(blank=True, db_column='EsDiagnostico', null=True)),
            ],
            options={
                'db_table': 'cuestionarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id_curso', models.AutoField(db_column='ID_Curso', primary_key=True, serialize=False)),
                ('nombrecurso', models.CharField(blank=True, db_column='NombreCurso', max_length=100, null=True)),
                ('descripcioncurso', models.TextField(blank=True, db_column='DescripcionCurso', null=True)),
                ('calificacion', models.DecimalField(blank=True, db_column='Calificacion', decimal_places=1, max_digits=2, null=True)),
                ('listavideos', models.JSONField(blank=True, db_column='ListaVideos', null=True)),
                ('listarecursos', models.JSONField(blank=True, db_column='ListaRecursos', null=True)),
            ],
            options={
                'db_table': 'curso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id_usuario', models.AutoField(db_column='ID_Usuario', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=50, null=True)),
                ('apellidopaterno', models.CharField(blank=True, db_column='ApellidoPaterno', max_length=50, null=True)),
                ('apellidomaterno', models.CharField(blank=True, db_column='ApellidoMaterno', max_length=50, null=True)),
                ('correoalternativo', models.CharField(blank=True, db_column='CorreoAlternativo', max_length=100, null=True)),
                ('numerocelular', models.CharField(blank=True, db_column='NumeroCelular', max_length=15, null=True)),
                ('descripcionperfil', models.TextField(blank=True, db_column='DescripcionPerfil', null=True)),
                ('fotoperfil', models.CharField(blank=True, db_column='FotoPerfil', max_length=100, null=True)),
                ('correoelectronico', models.CharField(blank=True, db_column='CorreoElectronico', max_length=100, null=True)),
                ('contrasena', models.CharField(blank=True, db_column='Contrasena', max_length=80, null=True)),
            ],
            options={
                'db_table': 'docente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estudiantes',
            fields=[
                ('id_usuario', models.AutoField(db_column='ID_Usuario', primary_key=True, serialize=False)),
                ('nickname', models.CharField(blank=True, db_column='Nickname', max_length=50, null=True)),
                ('nivelconocimiento', models.CharField(blank=True, db_column='NivelConocimiento', max_length=12, null=True)),
                ('fotoperfil', models.CharField(blank=True, db_column='FotoPerfil', max_length=100, null=True)),
                ('correoelectronico', models.CharField(blank=True, db_column='CorreoElectronico', max_length=100, null=True)),
                ('contrasena', models.CharField(blank=True, db_column='Contrasena', max_length=50, null=True)),
            ],
            options={
                'db_table': 'estudiantes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inscripciones',
            fields=[
                ('id_inscripcion', models.AutoField(db_column='ID_Inscripcion', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'inscripciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Opciones',
            fields=[
                ('id_opciones', models.AutoField(db_column='ID_Opciones', primary_key=True, serialize=False)),
                ('escorrecta', models.IntegerField(blank=True, db_column='EsCorrecta', null=True)),
            ],
            options={
                'db_table': 'opciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Preguntas',
            fields=[
                ('id_pregunta', models.AutoField(db_column='ID_Pregunta', primary_key=True, serialize=False)),
                ('textopregunta', models.TextField(blank=True, db_column='TextoPregunta', null=True)),
                ('textoopcion', models.TextField(blank=True, db_column='TextoOpcion', null=True)),
                ('imagenpregunta', models.CharField(blank=True, db_column='ImagenPregunta', max_length=255, null=True)),
            ],
            options={
                'db_table': 'preguntas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Problemas',
            fields=[
                ('id_problemas', models.AutoField(db_column='ID_Problemas', primary_key=True, serialize=False)),
                ('tituloproblema', models.CharField(blank=True, db_column='TituloProblema', max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, db_column='Descripcion', null=True)),
                ('solucion', models.TextField(blank=True, db_column='Solucion', null=True)),
            ],
            options={
                'db_table': 'problemas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recursosapoyo',
            fields=[
                ('id_recurso', models.AutoField(db_column='ID_Recurso', primary_key=True, serialize=False)),
                ('titulorecurso', models.CharField(blank=True, db_column='TituloRecurso', max_length=100, null=True)),
                ('urlrecurso', models.CharField(blank=True, db_column='URLRecurso', max_length=255, null=True)),
            ],
            options={
                'db_table': 'recursosapoyo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id_video', models.AutoField(db_column='ID_Video', primary_key=True, serialize=False)),
                ('titulovideo', models.CharField(blank=True, db_column='TituloVideo', max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, db_column='Descripcion', null=True)),
                ('video', models.CharField(blank=True, db_column='Video', max_length=255, null=True)),
            ],
            options={
                'db_table': 'video',
                'managed': False,
            },
        ),
    ]
