# Generated by Django 5.1.5 on 2025-03-02 20:11

import uuid
import yueLearningApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yueLearningApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_id', models.IntegerField()),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('fecha_expiracion', models.DateTimeField(default=yueLearningApp.models.default_expiration)),
            ],
            options={
                'db_table': 'email_verification_tokens',
            },
        ),
    ]
