# Generated by Django 5.1.5 on 2025-03-24 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yueLearningApp', '0003_docente_contrasena_estudiantes_contrasena'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='imagen_url',
            field=models.URLField(blank=True, db_column='ImagenURL', max_length=500, null=True),
        ),
    ]
