# Generated by Django 5.1.5 on 2025-04-23 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yueLearningApp', '0004_curso_imagen_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecursoApoyo',
            fields=[
                ('id_recurso', models.AutoField(db_column='ID_Recurso', primary_key=True, serialize=False)),
                ('titulorecurso', models.CharField(blank=True, db_column='TituloRecurso', max_length=100, null=True)),
                ('urlrecurso', models.CharField(blank=True, db_column='URLRecurso', max_length=255, null=True)),
            ],
            options={
                'db_table': 'recursosapoyo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id_video', models.AutoField(db_column='ID_Video', primary_key=True, serialize=False)),
                ('titulovideo', models.CharField(blank=True, db_column='TituloVideo', max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, db_column='Descripcion', null=True)),
                ('video', models.CharField(blank=True, db_column='Video', max_length=255, null=True)),
            ],
            options={
                'db_table': 'video',
                'managed': False,
            },
        ),
    ]
