# Generated by Django 5.1.5 on 2025-05-03 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yueLearningApp', '0006_cuestionario_pregunta_opcion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opcion',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='opcion',
            table='opciones',
        ),
    ]
