# Generated by Django 5.1.5 on 2025-05-18 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yueLearningApp', '0007_alter_opcion_options_alter_opcion_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalificacionCurso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('calificacion', models.IntegerField()),
                ('id_curso', models.ForeignKey(db_column='ID_Curso', on_delete=django.db.models.deletion.CASCADE, to='yueLearningApp.curso')),
                ('id_usuario', models.ForeignKey(db_column='ID_Usuario', on_delete=django.db.models.deletion.CASCADE, to='yueLearningApp.estudiantes')),
            ],
            options={
                'db_table': 'calificacion_curso',
                'unique_together': {('id_curso', 'id_usuario')},
            },
        ),
    ]
