# Generated by Django 5.1.5 on 2025-05-20 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yueLearningApp', '0008_calificacioncurso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problema',
            fields=[
                ('id_problema', models.AutoField(db_column='ID_Problema', primary_key=True, serialize=False)),
                ('tituloproblema', models.CharField(blank=True, db_column='TituloProblema', max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, db_column='Descripcion', null=True)),
                ('solucion', models.TextField(blank=True, db_column='Solucion', null=True)),
                ('id_curso', models.ForeignKey(blank=True, db_column='ID_Curso', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='yueLearningApp.curso')),
            ],
            options={
                'db_table': 'problema',
            },
        ),
    ]
